###Listado de todos los tuits
GET {{URL}}/tuits/


###Listado de un tuits por codigo
GET {{URL}}/tuits/3

###Postear un tuit
POST {{URL}}/tuits
Content-Type: application/json

{
    "message": "Como estan?"
}


###|Modificar un tuit
PATCH {{URL}}/tuits/1
Content-Type: application/json

{
    "message": "Chao mundo"
}


###Eliminar un tuit
DELETE {{URL}}/tuits/2
Content-Type: application/json
